name: Testing and validation

on: [push, pull_request]

jobs:

  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16.x ]

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Run linter
      run: npm run lint

  test:
    name: Tests
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16.x ]

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Run tests
      run: npm test -- --configuration=ci

  test_build:
    name: Test build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16.x ]
  
    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Build
      run: npm run build
